# Site
repository: rubentea16/rubentea16.github.io
favicon: images/favicon.ico

# Personal info
name: Ruben Stefanus
title: Machine Learning Engineer
email: rstefanus16@gmail.com

darkmode: true

# Social links
github_username:  rubentea16
instagram_username: rubenstefanus
linkedin_username: rubenstefanus

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Ruben and I'm a Machine Learning Engineer. I do data science, AI and enjoys to solve problem using data.
  I trust Data and Technology it's not only about complex/fancy things, but from my opinion it's all about use it to give social impact and enhance every aspect of our life.
  And then i realize it has huge power same as government power to make changes of our life.
  I like to exploring and learning something new about data and tech industry, feel free to connect and have conversation with me.   
  The things that I currently have the most experience working with are:<mark>Python</mark>,
  <mark>Machine Learning</mark>,
  <mark>NLP</mark>,
  <mark>Keras</mark>,
  <mark>Tensorflow</mark>,
  <mark>Scikit-Learn</mark>,
  <mark>Docker</mark>,
  <mark>SQL</mark>,
  <mark>Pandas</mark> and
  <mark>GCP</mark> services.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  My hobbies are -> <mark>Reading books</mark>, <mark>Watching movies</mark>, <mark>Listen music</mark>, <mark>Do machine learning stuff</mark>.

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
